$(document).ready(function () {
    $('input[id=cheese]').change(function()
    {
        if($(this).prop('checked'))
        $('.type').show();
        else
            $('.type').hide();
    });
    
     $('input[id=sauce]').change(function()
    {
        if($(this).prop('checked'))
        $('#type1').show();
        else
        $('#type1').hide();
    });
    
    $('input[id=sauce1]').change(function()
    {
        if($(this).prop('checked'))
        $('#type2').show();
        else 
        $('#type2').hide();
    });
    
    $('input[id=sauce2]').change(function()
    {
        if($(this).prop('checked'))
        $('#type3').show();
        else
            $('#type3').hide();
    });
    
    $('input[id=sauce3]').change(function()
    {
        if($(this).prop('checked'))
        $('#type4').show();
        else
            $('#type4').hide();
    });
    
    $('input[id=sauce4]').change(function()
    {
        if($(this).prop('checked'))
        $('#type5').show();
        else
            $('#type5').hide();
    });
    
    $('input[id=sauce5]').change(function()
    {
        if($(this).prop('checked'))
        $('#type6').show();
        else
            $('#type6').hide();
    });
    
     $('input[id=meat]').change(function()
    {
        if($(this).prop('checked'))
        $('.pepperoni').show();
        else
            $('.pepperoni').hide();
    });
    
    $('input[id=isausage]').change(function()
    {
        if($(this).prop('checked'))
        $('.italian').show();
        else
            $('.italian').hide();
    });
    $('input[id=ssausage]').change(function()
    {
        if($(this).prop('checked'))
        $('.sliced').show();
        else
            $('.sliced').hide();
    });
    $('input[id=beefy]').change(function()
    {
        if($(this).prop('checked'))
        $('.beef').show();
        else
            $('.beef').hide();
    });
    $('input[id=psteak]').change(function()
    {
        if($(this).prop('checked'))
        $('.philly').show();
        else
            $('.philly').hide();
    });
    $('input[id=hamy]').change(function()
    {
        if($(this).prop('checked'))
        $('.ham').show();
        else
            $('.ham').hide();
    });
    $('input[id=bac]').change(function()
    {
        if($(this).prop('checked'))
        $('.bacon').show();
        else
            $('.bacon').hide();
    });
    $('input[id=sal]').change(function()
    {
        if($(this).prop('checked'))
        $('.salami').show();
        else
            $('.salami').hide();
    });
    
    $('input[id=chick]').change(function()
    {
        if($(this).prop('checked'))
        $('.chicken').show();
        else
            $('.chicken').hide();
    });
    $('input[id=cheddar]').change(function()
    {
        if($(this).prop('checked'))
        $('.ccheese').show();
        else
            $('.ccheese').hide();
    });
    $('input[id=feta]').change(function()
    {
        if($(this).prop('checked'))
        $('.fcheese').show();
        else
            $('.fcheese').hide();
    });
    $('input[id=parmesian]').change(function()
    {
        if($(this).prop('checked'))
        $('.sparmesian').show();
        else
            $('.sparmesian').hide();
    });
    $('input[id=provolone]').change(function()
    {
        if($(this).prop('checked'))
        $('.sprovolone').show();
        else
            $('.sprovolone').hide();
    });
    $('input[id=banana]').change(function()
    {
        if($(this).prop('checked'))
        $('.bpeppers').show();
        else
            $('.bpeppers').hide();
    });
    $('input[id=black]').change(function()
    {
        if($(this).prop('checked'))
        $('.olives').show();
        else
            $('.olives').hide();
    });
    $('input[id=gar]').change(function()
    {
        if($(this).prop('checked'))
        $('.garlic').show();
        else
            $('.garlic').hide();
    });
    $('input[id=green]').change(function()
    {
        if($(this).prop('checked'))
        $('.gpeppers').show();
        else
            $('.gpeppers').hide();
    });
    $('input[id=jalapeno]').change(function()
    {
        if($(this).prop('checked'))
        $('.jpeppers').show();
        else
            $('.jpeppers').hide();
    });
    $('input[id=hot]').change(function()
    {
        if($(this).prop('checked'))
        $('.hotsauce').show();
        else
            $('.hotsauce').hide();
    });
    $('input[id=diced]').change(function()
    {
        if($(this).prop('checked'))
        $('.dtomato').show();
        else
            $('.dtomato').hide();
    });
    $('input[id=tomato]').change(function()
    {
        if($(this).prop('checked'))
        $('.tomatoes').show();
        else
            $('.tomatoes').hide();
    });
    $('input[id=spi]').change(function()
    {
        if($(this).prop('checked'))
        $('.spinach').show();
        else
            $('.spinach').hide();
    });
    $('input[id=roasted]').change(function()
    {
        if($(this).prop('checked'))
        $('.rpeppers').show();
        else
            $('.rpeppers').hide();
    });
    $('input[id=onion]').change(function()
    {
        if($(this).prop('checked'))
        $('.onions').show();
        else
            $('.onions').hide();
    });
    $('input[id=pine]').change(function()
    {
        if($(this).prop('checked'))
        $('.pineapple').show();
        else
            $('.pineapple').hide();
    });
    $('input[id=mush]').change(function()
    {
        if($(this).prop('checked'))
        $('.mushroom').show();
        else
            $('.mushroom').hide();
    });
    
    
    
    
    
 
});